global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'targeting-engine'
    static_configs:
      - targets: ['targeting-engine:8080']
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true